[pytest]
testpaths = tests
pythonpath = .
filterwarnings =
    ignore::DeprecationWarning
    ignore::UserWarning
    ignore::RuntimeWarning
asyncio_mode = auto
asyncio_default_fixture_loop_scope = function
